apiVersion: v1
kind: Deployment
metadata:
	name: sample_voting_app
	labels:
     	app: sample_voting_app
spec:
	template:
		metadata: 
			labels: 
			   app: redis_votingapp
	    spec:
	    	containers:
	    	- name: redis
	    	  image: redis
	    	  ports:
	    	  - containerPort: 6379
	replicas: 1
	selector:
		matchLabels:
			app: redis_votingapp