apiVersion: v1
kind: Deployment
metadata:
	name: sample_voting_app
	labels:
     	app: sample_voting_app
spec:
	template:
		metadata: 
			labels: 
			   app: postgres_votingapp
	    spec:
	    	containers:
	    	- name: postgres
	    	  image: postgres:9.4 
	    	  ports:
	    	  - containerPort: 5432
	replicas: 1
	selector:
		matchLabels:
			app: postgres_votingapp